[package]
name = "mrd-render-d3d11"
version = "0.1.0"
edition = "2021"

[dependencies]
mrd-render = { path = "../mrd-render" }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.52", features = [
  "Win32_Foundation",
  "Win32_Graphics_Direct3D",
  "Win32_Graphics_Direct3D11",
  "Win32_Graphics_Dxgi",
  "Win32_Graphics_Dxgi_Common",
  "Win32_UI_WindowsAndMessaging",
] }

[dev-dependencies]
mrd-observability = { path = "../mrd-observability" }
serde_json = { workspace = true }
