[package]
name = "mrd-application"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait = "0.1"
mrd-proto = { path = "../mrd-proto" }
mrd-session = { path = "../mrd-session" }
mrd-signal-proto = { path = "../mrd-signal-proto" }
tokio.workspace = true
tracing.workspace = true
