[package]
name = "realtime-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "realtime_server"
path = "src/lib.rs"

[dependencies]
axum = { workspace = true, features = ["ws"] }
futures-util = "0.3"
mrd-proto = { path = "../../crates/mrd-proto" }
mrd-identity = { path = "../../crates/mrd-identity" }
mrd-signal-client = { path = "../../crates/mrd-signal-client" }
mrd-signal-proto = { path = "../../crates/mrd-signal-proto" }
serde.workspace = true
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
ring.workspace = true

[[bin]]
name = "realtime-server"
path = "src/main.rs"
