[package]
name = "mrd-encode-vvenc"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mrd-pipeline-core = { path = "../mrd-pipeline-core" }
vvenc = { version = "0.1.2", optional = true }

[features]
default = []
production-vvc-software-codec = ["software-vvenc"]
software-vvenc = ["dep:vvenc"]
