[package]
name = "mrd-encode-vvenc"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mrd-pipeline-core = { path = "../mrd-pipeline-core" }
vvenc-sys = { version = "0.1.0", optional = true }

[dev-dependencies]
mrd-decode = { path = "../mrd-decode", features = ["production-vvc-software-codec"] }

[features]
default = []
production-vvc-software-codec = ["software-vvenc"]
software-vvenc = ["dep:vvenc-sys"]
