[package]
name = "mrd-render-macos"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mrd-render = { path = "../mrd-render" }

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics-types = "0.2"
dispatch2 = "0.3"
metal = "0.33"
objc = "0.2"

[dev-dependencies]
mrd-observability = { path = "../mrd-observability" }
serde_json = { workspace = true }
