[package]
name = "mrd-encode-openh264"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mrd-pipeline-core = { path = "../mrd-pipeline-core" }
openh264 = "0.8"
thiserror.workspace = true

[dev-dependencies]
mrd-observability = { path = "../mrd-observability" }
serde_json = { workspace = true }
