#!/usr/bin/env python3
"""Deterministic PNG exports. Never trace/repaint the selected brand artwork."""
import argparse
import hashlib
import io
import json
from pathlib import Path

from PIL import Image, ImageDraw, __version__ as pillow_version

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "branding/launcher-source.png"
RES = ROOT / "app/src/main/res"
DENSITIES = {"mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}
BACKGROUND = "#F8FAFC"
SOURCE_SHA256 = "84a76a25267aa92a21178ac511ad725959a4481c721878da22f50224f27a1b53"


def build():
    raw = SOURCE.read_bytes()
    if hashlib.sha256(raw).hexdigest() != SOURCE_SHA256:
        raise SystemExit("Source changed: review artwork and update the pinned source SHA first")
    image = Image.open(io.BytesIO(raw))
    assert image.format == "PNG" and image.mode == "RGBA"
    bbox = image.getbbox()
    symbol = image.crop(bbox)
    outputs = {}

    def png(path, image):
        buffer = io.BytesIO()
        image.save(buffer, format="PNG", optimize=False, compress_level=9)
        outputs[path] = buffer.getvalue()

    def foreground(size, span):
        scale = span / max(symbol.size)
        mark = symbol.resize(tuple(round(n * scale) for n in symbol.size), Image.Resampling.LANCZOS)
        result = Image.new("RGBA", (size, size))
        result.alpha_composite(mark, ((size - mark.width) // 2, (size - mark.height) // 2))
        return result

    for density, scale in DENSITIES.items():
        # 108dp layers; max alpha bounds 51dp, core artwork inside the 66dp safe circle.
        fg = foreground(round(108 * scale), round(51 * scale))
        png(f"drawable-{density}/ic_launcher_foreground.png", fg)
        mono = Image.new("RGBA", fg.size, (255, 255, 255, 0))
        mono.putalpha(fg.getchannel("A"))
        png(f"drawable-{density}/ic_launcher_monochrome.png", mono)
        # Legacy launcher is a separate 48dp export, not a downscaled 108dp layer.
        size = round(48 * scale)
        legacy = Image.new("RGBA", (size, size), BACKGROUND)
        legacy.alpha_composite(foreground(size, round(34 * scale)))
        png(f"mipmap-{density}/ic_launcher.png", legacy)
        mask = Image.new("L", (size * 4, size * 4))
        ImageDraw.Draw(mask).ellipse((0, 0, size * 4 - 1, size * 4 - 1), fill=255)
        legacy.putalpha(mask.resize((size, size), Image.Resampling.LANCZOS))
        png(f"mipmap-{density}/ic_launcher_round.png", legacy)

    for api in (26, 33):
        mono = '\n    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />' if api == 33 else ""
        xml = ('<?xml version="1.0" encoding="utf-8"?>\n'
               '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
               '    <background android:drawable="@color/ic_launcher_background" />\n'
               '    <foreground android:drawable="@drawable/ic_launcher_foreground" />'
               + mono + '\n</adaptive-icon>\n').encode()
        for name in ("ic_launcher", "ic_launcher_round"):
            outputs[f"mipmap-anydpi-v{api}/{name}.xml"] = xml
    outputs["values/launcher_colors.xml"] = (
        '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
        f'    <color name="ic_launcher_background">{BACKGROUND}</color>\n'
        '</resources>\n').encode()
    metadata = {
        "source": "branding/launcher-source.png", "source_sha256": SOURCE_SHA256,
        "status": "B optical-v2 candidate; Android/device and cross-platform release acceptance pending",
        "source_size_px": list(image.size), "source_alpha_bbox_px": list(bbox),
        "pillow_version": pillow_version, "resampling": "LANCZOS", "png_compress_level": 9,
        "adaptive_layer_dp": 108, "adaptive_symbol_max_span_dp": 51,
        "legacy_canvas_dp": 48, "legacy_symbol_max_span_dp": 34,
        "background": BACKGROUND, "monochrome": "white RGB with identical foreground alpha; system applies tint",
        "outputs": {path: hashlib.sha256(data).hexdigest() for path, data in sorted(outputs.items())},
    }
    return outputs, (json.dumps(metadata, indent=2, ensure_ascii=False) + "\n").encode()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Compare every generated byte; do not write")
    args = parser.parse_args()
    outputs, metadata = build()
    files = {RES / path: data for path, data in outputs.items()}
    files[ROOT / "branding/launcher-provenance.json"] = metadata
    for path, data in files.items():
        if args.check:
            if not path.exists() or path.read_bytes() != data:
                raise SystemExit(f"Generated output differs: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    print(f"PASS: {'checked' if args.check else 'generated'} {len(files)} pinned-source outputs")


if __name__ == "__main__":
    main()
