[package]
name = "mrd-hardware"
version = "0.1.0"
edition = "2021"

[dependencies]
mrd-pipeline-core = { path = "../mrd-pipeline-core" }
mrd-encode-nvenc = { path = "../mrd-encode-nvenc", optional = true }
mrd-encode-openh264 = { path = "../mrd-encode-openh264", optional = true }
mrd-decode-nvdec = { path = "../mrd-decode-nvdec", optional = true }
mrd-decode = { path = "../mrd-decode", optional = true }
thiserror = "1"
log = "0.4"

[features]
default = ["nvenc", "openh264", "nvdec", "software_decoder"]
nvenc = ["mrd-encode-nvenc"]
openh264 = ["mrd-encode-openh264"]
nvdec = ["mrd-decode-nvdec"]
software_decoder = ["mrd-decode"]
