[package]
name = "mrd-signal-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mrd-proto = { path = "../mrd-proto" }
mrd-signal-proto = { path = "../mrd-signal-proto" }
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
mrd-identity = { path = "../mrd-identity" }
ring.workspace = true
