import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest';
import fixture from './__fixtures__/browser-relay-directory.json';
import * as directoryModule from './browserRelayDirectory';
const cryptoModuleName = 'node:crypto';
const { webcrypto } = await import(/* @vite-ignore */ cryptoModuleName) as { webcrypto: Crypto };
const directory = directoryModule;
const binding = { grant: fixture.grant, targetDeviceId: fixture.target_device_id, keyId: fixture.key_id, publicKey: fixture.public_key, nowMs: fixture.now_ms };

beforeEach(() => vi.stubGlobal('crypto', webcrypto));
afterEach(() => { vi.restoreAllMocks(); vi.useRealTimers(); vi.unstubAllGlobals(); });

describe('trusted browser relay directory', () => {
  it('matches the binary canonical bytes generated by the actual Python backend', () => {
    const bytes = directory.canonicalRelayDirectoryBytes?.(fixture.access.directory.payload) as Uint8Array | undefined;
    expect(bytes && Array.from(bytes, b => b.toString(16).padStart(2, '0')).join('')).toBe(fixture.canonical_hex);
  });
  it('verifies the backend signature and derives only authorized TURN and STUN servers', async () => {
    expect(await directory.verifyBrowserRelayAccess?.(fixture.access, binding)).toMatchObject({
      iceTransportPolicy: 'all',
      iceServers: [
        { urls: fixture.access.credentials[0]!.urls, username: 'fixture-user', credential: 'fixture-password' },
        { urls: ['stun:203.0.113.10:3478'] },
      ],
    });
  });
  it('does not add STUN servers or accept direct routing for relay-only grants', async () => {
    expect(await directory.verifyBrowserRelayAccess?.(fixture.access, {
      ...binding, grant: { ...fixture.grant, route_policy: 'relay_only' },
    })).toMatchObject({ iceTransportPolicy: 'relay', iceServers: [{ urls: fixture.access.credentials[0]!.urls, username: 'fixture-user', credential: 'fixture-password' }] });
  });
  it.each(['wrong peer', 'wrong signer', 'wrong public key', 'wrong session', 'wrong directory', 'wrong policy', 'wrong generation',
    'unsupported route', 'altered endpoint', 'expired directory', 'expired credential', 'extra credential', 'wrong digest'])('rejects %s instead of trusting unbound TURN credentials', async condition => {
    expect(typeof directory.verifyBrowserRelayAccess).toBe('function');
    if (!directory.verifyBrowserRelayAccess) return;
    const access = structuredClone(fixture.access);
    const expected = structuredClone(binding);
    if (condition === 'wrong peer') expected.targetDeviceId = '987654321098';
    if (condition === 'wrong signer') expected.keyId = '0'.repeat(64);
    if (condition === 'wrong public key') expected.publicKey[0] = expected.publicKey[0]! ^ 1;
    if (condition === 'wrong session') expected.grant.session_id = 'another-session';
    if (condition === 'wrong directory') expected.grant.relay_directory_id = 'another-directory';
    if (condition === 'wrong policy') expected.grant.backend_policy_revision++;
    if (condition === 'wrong generation') expected.grant.relay_generation = 1;
    if (condition === 'unsupported route') expected.grant.route_policy = 'unrestricted';
    if (condition === 'altered endpoint') access.directory.payload.candidates[0]!.endpoints[0]!.host = 'attacker.example';
    if (condition === 'expired directory') expected.nowMs = fixture.access.directory.payload.expires_at_ms;
    if (condition === 'expired credential') access.credentials[0]!.expires_at_unix_seconds = Math.floor(expected.nowMs / 1000);
    if (condition === 'extra credential') access.credentials.push({ ...access.credentials[0]!, node_id: 'attacker-node' });
    if (condition === 'wrong digest') access.relay_url_digest = '0'.repeat(64);
    await expect(directory.verifyBrowserRelayAccess(access, expected)).rejects.toThrow();
  });

  it.each(['access fields', 'signature fields', 'payload fields', 'fractional issue time', 'unsafe issue time', 'candidate fields',
    'generation type', 'directory id type', 'relay digest format', 'signer type', 'signer format',
    'signature type', 'signature length', 'signature encoding', 'noncanonical signature',
    'credentials type', 'credentials count', 'credential fields', 'credential node type', 'credential username type',
    'credential secret type', 'credential control character', 'credential expiry type', 'credential URLs type',
    'credential URL type', 'credential URL length', 'credential URL shape', 'duplicate credential URLs',
    'endpoint transport type'])('rejects malformed %s before scheduling an issue-time wait', async condition => {
    vi.useFakeTimers({ toFake: ['setTimeout', 'clearTimeout', 'performance'] });
    vi.spyOn(Date, 'now').mockReturnValue(fixture.now_ms);
    const access = structuredClone(fixture.access);
    access.directory.payload.issued_at_ms = fixture.now_ms + 1500;
    if (condition === 'access fields') Object.assign(access, { unbound: true });
    if (condition === 'signature fields') Object.assign(access.directory, { unbound: true });
    if (condition === 'payload fields') Object.assign(access.directory.payload, { unbound: true });
    if (condition === 'fractional issue time') access.directory.payload.issued_at_ms += 0.5;
    if (condition === 'unsafe issue time') access.directory.payload.issued_at_ms = Number.MAX_SAFE_INTEGER + 1;
    if (condition === 'candidate fields') Object.assign(access.directory.payload.candidates[0]!, { unbound: true });
    if (condition === 'generation type') Object.assign(access, { generation: '0' });
    if (condition === 'directory id type') Object.assign(access, { directory_id: null });
    if (condition === 'relay digest format') access.relay_url_digest = 'g'.repeat(64);
    if (condition === 'signer type') Object.assign(access.directory, { signing_key_id: null });
    if (condition === 'signer format') access.directory.signing_key_id = 'g'.repeat(64);
    if (condition === 'signature type') Object.assign(access.directory, { signature_b64: null });
    if (condition === 'signature length') access.directory.signature_b64 = 'A'.repeat(89);
    if (condition === 'signature encoding') access.directory.signature_b64 = '*'.repeat(86) + '==';
    if (condition === 'noncanonical signature') access.directory.signature_b64 = access.directory.signature_b64.slice(0, 85) + 'B==';
    if (condition === 'credentials type') Object.assign(access, { credentials: null });
    if (condition === 'credentials count') access.credentials = [];
    if (condition === 'credential fields') Object.assign(access.credentials[0]!, { unbound: true });
    if (condition === 'credential node type') Object.assign(access.credentials[0]!, { node_id: null });
    if (condition === 'credential username type') Object.assign(access.credentials[0]!, { username: null });
    if (condition === 'credential secret type') Object.assign(access.credentials[0]!, { credential: null });
    if (condition === 'credential control character') access.credentials[0]!.credential = 'secret\u0000';
    if (condition === 'credential expiry type') access.credentials[0]!.expires_at_unix_seconds += 0.5;
    if (condition === 'credential URLs type') Object.assign(access.credentials[0]!, { urls: null });
    if (condition === 'credential URL type') Object.assign(access.credentials[0]!, { urls: [null] });
    if (condition === 'credential URL length') access.credentials[0]!.urls = ['turn:' + 'a'.repeat(513)];
    if (condition === 'credential URL shape') access.credentials[0]!.urls = ['https://attacker.example'];
    if (condition === 'duplicate credential URLs') access.credentials[0]!.urls.push(access.credentials[0]!.urls[0]!);
    if (condition === 'endpoint transport type') Object.assign(access.directory.payload.candidates[0]!.endpoints[0]!, { transport: { toString: () => 'udp' } });
    const controller = new AbortController();
    const result = directory.waitUntilRelayDirectoryIssued(access, controller.signal).catch(error => error);
    try {
      await Promise.resolve();
      expect(vi.getTimerCount()).toBe(0);
    } finally {
      controller.abort();
    }
    expect(await result).toBeInstanceOf(Error);
  });

  it('exposes only frozen bounded diagnostics for a not-yet-valid signed directory', async () => {
    const nowMs = fixture.access.directory.payload.issued_at_ms - 1;
    let rejection: unknown;
    try { await directory.verifyBrowserRelayAccess(fixture.access, { ...binding, nowMs }); }
    catch (error) { rejection = error; }
    expect(rejection).toBeInstanceOf(directory.BrowserRelayDirectoryValidityError);
    const error = rejection as directoryModule.BrowserRelayDirectoryValidityError;
    expect(error.message).toBe('远程中继目录无效或不属于当前会话');
    expect(Object.isFrozen(error.diagnostics)).toBe(true);
    expect(error.diagnostics).toEqual({
      message_type: 'relay_directory', generation_matches: true, directory_matches: true,
      session_matches: true, policy_matches: true, key_pin_matches: true, route_allowed: true,
      issued_delta_ms: 1, expiry_remaining_ms: fixture.access.directory.payload.expires_at_ms - nowMs,
    });
  });
});
