import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest';
import fixture from './__fixtures__/browser-relay-directory.json';
import * as directoryModule from './browserRelayDirectory';
const cryptoModuleName = 'node:crypto';
const { webcrypto } = await import(/* @vite-ignore */ cryptoModuleName) as { webcrypto: Crypto };
const directory = directoryModule as Record<string, (...args: any[]) => any>;
const binding = { grant: fixture.grant, targetDeviceId: fixture.target_device_id, keyId: fixture.key_id, publicKey: fixture.public_key, nowMs: fixture.now_ms };

beforeEach(() => vi.stubGlobal('crypto', webcrypto));
afterEach(() => vi.unstubAllGlobals());

describe('trusted browser relay directory', () => {
  it('matches the binary canonical bytes generated by the actual Python backend', () => {
    const bytes = directory.canonicalRelayDirectoryBytes?.(fixture.access.directory.payload) as Uint8Array | undefined;
    expect(bytes && Array.from(bytes, b => b.toString(16).padStart(2, '0')).join('')).toBe(fixture.canonical_hex);
  });
  it('verifies the backend signature and derives only authorized TURN and STUN servers', async () => {
    expect(await directory.verifyBrowserRelayAccess?.(fixture.access, binding)).toMatchObject({
      iceTransportPolicy: 'all',
      iceServers: [
        { urls: fixture.access.credentials[0]!.urls, username: 'fixture-user', credential: 'fixture-password' },
        { urls: ['stun:203.0.113.10:3478'] },
      ],
    });
  });
  it('does not add STUN servers or accept direct routing for relay-only grants', async () => {
    expect(await directory.verifyBrowserRelayAccess?.(fixture.access, {
      ...binding, grant: { ...fixture.grant, route_policy: 'relay_only' },
    })).toMatchObject({ iceTransportPolicy: 'relay', iceServers: [{ urls: fixture.access.credentials[0]!.urls, username: 'fixture-user', credential: 'fixture-password' }] });
  });
  it.each(['wrong peer', 'wrong signer', 'altered endpoint', 'expired directory', 'extra credential', 'wrong digest'])('rejects %s instead of trusting unbound TURN credentials', async condition => {
    expect(typeof directory.verifyBrowserRelayAccess).toBe('function');
    if (!directory.verifyBrowserRelayAccess) return;
    const access = structuredClone(fixture.access);
    const expected = structuredClone(binding);
    if (condition === 'wrong peer') expected.targetDeviceId = '987654321098';
    if (condition === 'wrong signer') expected.keyId = '0'.repeat(64);
    if (condition === 'altered endpoint') access.directory.payload.candidates[0]!.endpoints[0]!.host = 'attacker.example';
    if (condition === 'expired directory') expected.nowMs = fixture.access.directory.payload.expires_at_ms;
    if (condition === 'extra credential') access.credentials.push({ ...access.credentials[0]!, node_id: 'attacker-node' });
    if (condition === 'wrong digest') access.relay_url_digest = '0'.repeat(64);
    await expect(directory.verifyBrowserRelayAccess(access, expected)).rejects.toThrow();
  });
});
